;;; opencl-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from opencl-c-mode.el

(add-to-list 'auto-mode-alist '("\\.cl\\'" . opencl-c-mode))
(add-to-list 'auto-mode-alist '("\\.clc\\'" . opencl-c-mode))
(add-to-list 'auto-mode-alist '("\\.opencl\\'" . opencl-c-mode))
(autoload 'opencl-c-mode "opencl-c-mode" "\
Major mode for editing OpenCL C kernels.

\\{opencl-c-mode-map}

(fn)" t)

;;; End of scraped data

(provide 'opencl-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; opencl-mode-autoloads.el ends here
